"""
HTML report template for A8 Report Builder.
Inline styles — no external dependencies, opens in any browser.
"""

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{app_name} QA Report</title>
<style>
  :root {{
    --pass:#1a7a4a; --fail:#c0392b; --error:#e67e22; --neutral:#7f8c8d;
    --bg:#f5f6fa; --card:#fff; --header:#2c3e50; --sub:#34495e;
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Segoe UI',Arial,sans-serif;background:var(--bg);color:#2c3e50;font-size:14px}}
  header{{background:var(--header);color:#fff;padding:24px 40px}}
  header h1{{font-size:20px;margin-bottom:6px}}
  header p{{opacity:.7;font-size:12px;line-height:1.8}}
  .summary{{display:flex;gap:16px;padding:24px 40px;flex-wrap:wrap}}
  .card{{background:var(--card);border-radius:8px;padding:20px 24px;flex:1;min-width:120px;
         box-shadow:0 1px 4px rgba(0,0,0,.1);text-align:center}}
  .card .num{{font-size:34px;font-weight:700;line-height:1}}
  .card .lbl{{font-size:11px;color:var(--neutral);margin-top:6px;text-transform:uppercase;letter-spacing:.5px}}
  .card.pass .num{{color:var(--pass)}}
  .card.fail .num{{color:var(--fail)}}
  .card.err  .num{{color:var(--error)}}
  section{{padding:0 40px 40px}}
  h2{{font-size:14px;font-weight:700;margin:28px 0 14px;border-bottom:2px solid #eee;
      padding-bottom:8px;text-transform:uppercase;letter-spacing:.5px;color:var(--sub)}}
  .module-row{{display:flex;align-items:center;gap:12px;margin-bottom:10px}}
  .module-row .name{{width:200px;font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
  .module-row .bar{{flex:1;height:14px;background:#ecf0f1;border-radius:7px;overflow:hidden}}
  .module-row .fill{{height:100%;background:var(--pass);transition:width .3s}}
  .module-row .pct{{width:48px;text-align:right;font-size:12px;color:var(--neutral)}}
  table{{width:100%;border-collapse:collapse;background:var(--card);border-radius:8px;
         overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.1)}}
  thead tr{{background:var(--sub)}}
  th{{padding:10px 14px;text-align:left;font-size:11px;color:#fff;font-weight:600;text-transform:uppercase;letter-spacing:.4px}}
  td{{padding:10px 14px;font-size:13px;border-bottom:1px solid #ecf0f1;vertical-align:top}}
  tbody tr:last-child td{{border:none}}
  tbody tr:hover{{background:#f8f9fb}}
  .badge{{display:inline-block;padding:2px 10px;border-radius:12px;font-size:11px;font-weight:700;text-transform:uppercase}}
  .badge.passed{{background:#d5f5e3;color:var(--pass)}}
  .badge.failed{{background:#fadbd8;color:var(--fail)}}
  .badge.error {{background:#fdebd0;color:var(--error)}}
  .badge.pending{{background:#eaecee;color:var(--neutral)}}
  .steps{{font-size:12px;color:#555;margin-top:5px;line-height:1.7}}
  .err-msg{{font-size:12px;color:var(--fail);margin-top:5px;font-style:italic}}
  .tc-id{{font-family:monospace;font-size:12px;color:var(--sub)}}
  footer{{text-align:center;padding:24px;font-size:11px;color:#aaa;border-top:1px solid #eee;margin-top:20px}}
</style>
</head>
<body>

<header>
  <h1>&#x1F9EA; {app_name} QA Execution Report</h1>
  <p>
    Application: <strong>{app_name}</strong> &nbsp;&bull;&nbsp;
    Run ID: <code>{run_id}</code> &nbsp;&bull;&nbsp;
    {timestamp} UTC &nbsp;&bull;&nbsp;
    Duration: {duration}
  </p>
</header>

<div class="summary">
  <div class="card"><div class="num">{total}</div><div class="lbl">Total Tests</div></div>
  <div class="card pass"><div class="num">{passed}</div><div class="lbl">Passed</div></div>
  <div class="card fail"><div class="num">{failed}</div><div class="lbl">Failed</div></div>
  <div class="card err"><div class="num">{error}</div><div class="lbl">Errors</div></div>
  <div class="card"><div class="num">{pass_rate}%</div><div class="lbl">Pass Rate</div></div>
</div>

<section>
  <h2>Results by Module</h2>
  {module_bars}

  <h2>Test Case Results</h2>
  <table>
    <thead>
      <tr>
        <th style="width:110px">TC ID</th>
        <th style="width:130px">Module</th>
        <th>Description &amp; Steps</th>
        <th style="width:90px">Status</th>
        <th style="width:90px">Duration</th>
        <th style="width:60px">Retries</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
</section>

{compliance_section}

<footer>
  Generated by QA Office &mdash; Agent A8 Report Builder &nbsp;&bull;&nbsp;
  QA Office &nbsp;&bull;&nbsp; {timestamp} UTC
</footer>
</body>
</html>
"""

COMPLIANCE_SECTION = """\
<section>
  <h2>SOC2 Audit Trail</h2>
  <table>
    <thead>
      <tr>
        <th style="width:220px">Property</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Run ID</td><td><code>{run_id}</code></td></tr>
      <tr><td>Run Hash (SHA-256)</td><td><code style="font-size:11px">{run_hash}</code></td></tr>
      <tr><td>Signed Timestamp</td><td>{signed_timestamp}</td></tr>
      <tr><td>Environment Health</td><td>{env_health}</td></tr>
      <tr><td>Seed Summary</td><td>{seed_summary}</td></tr>
      <tr><td>Chain of Custody</td><td>{chain_of_custody}</td></tr>
    </tbody>
  </table>
</section>"""
