"""Auto-generated by A14 POM Builder — do not edit manually."""

from .page0_page import Page0Page
from .page1_page import Page1Page
from .page2_page import Page2Page
from .page3_page import Page3Page
from .page4_page import Page4Page

__all__ = ['Page0Page', 'Page1Page', 'Page2Page', 'Page3Page', 'Page4Page']
