"""
Page Object for LoginPage — auto-generated by A14 POM Builder.
URL: http://localhost:3000/login
"""

from typing import Optional


class LoginPage:
    """Page Object for http://localhost:3000/login"""

    def __init__(self, page) -> None:
        self._page = page

    @property
    def email_input(self):
        """Email address input field"""
        return self._page.get_by_label("Email")

    @property
    def login_button(self):
        """Submit login form"""
        return self._page.get_by_role("button", name="Login")

    # Locator constants (class-level, for A3 cache lookup)
    EMAIL_INPUT = 'page.get_by_label("Email")'
    LOGIN_BUTTON = 'page.get_by_role("button", name="Login")'
