"""
Page Object for Page4 — auto-generated by A14 POM Builder.
URL: http://app/4
"""

from typing import Optional


class Page4Page:
    """Page Object for http://app/4"""

    def __init__(self, page) -> None:
        self._page = page

    @property
    def btn(self):
        """btn"""
        return self._page.get_by_role("button")

    # Locator constants (class-level, for A3 cache lookup)
    BTN = 'page.get_by_role("button")'
