"""
POM Writer — generates Python Page Object class files from PageMap data.
Output: tools/page_objects/<snake_name>_page.py
Pattern: CLASS_ATTR = page.get_by_label("Email address")
"""

import re
from pathlib import Path
from typing import List, Optional

from schemas import PageMap

_OUTPUT_DIR = Path(__file__).parent / "page_objects"


def _snake(name: str) -> str:
    """PascalCase → snake_case."""
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    return s.lower()


def _render_class(page_map: PageMap) -> str:
    lines = [
        '"""',
        f"Page Object for {page_map.page_name} — auto-generated by A14 POM Builder.",
        f"URL: {page_map.url}",
        '"""',
        "",
        "from typing import Optional",
        "",
        "",
        f"class {page_map.class_name}:",
        f'    """Page Object for {page_map.url}"""',
        "",
        "    def __init__(self, page) -> None:",
        "        self._page = page",
        "",
    ]

    for el in page_map.elements:
        locator_expr = el.locator.replace("page.", "self._page.")
        lines.append(f"    @property")
        lines.append(f"    def {el.python_name.lower()}(self):")
        lines.append(f'        """{el.description}"""')
        lines.append(f"        return {locator_expr}")
        lines.append("")

    # Class-level constants for stable references
    lines.append("    # Locator constants (class-level, for A3 cache lookup)")
    for el in page_map.elements:
        lines.append(f'    {el.python_name} = {repr(el.locator)}')

    return "\n".join(lines) + "\n"


def write_page_object(page_map: PageMap, output_dir: Optional[Path] = None) -> str:
    """Write one PageObject .py file. Returns path written."""
    out = output_dir or _OUTPUT_DIR
    out.mkdir(parents=True, exist_ok=True)

    filename = _snake(page_map.class_name) + ".py"
    path = out / filename
    path.write_text(_render_class(page_map), encoding="utf-8")
    return str(path)


def write_all(page_maps: List[PageMap], output_dir: Optional[Path] = None) -> List[str]:
    """Write all page objects. Returns list of file paths."""
    return [write_page_object(pm, output_dir) for pm in page_maps]


def write_init(page_maps: List[PageMap], output_dir: Optional[Path] = None) -> str:
    """Write __init__.py exporting all page classes."""
    out = output_dir or _OUTPUT_DIR
    out.mkdir(parents=True, exist_ok=True)

    lines = ['"""Auto-generated by A14 POM Builder — do not edit manually."""', ""]
    for pm in page_maps:
        module = _snake(pm.class_name)
        lines.append(f"from .{module} import {pm.class_name}")
    lines.append("")
    lines.append(f"__all__ = {[pm.class_name for pm in page_maps]!r}")
    lines.append("")

    init_path = out / "__init__.py"
    init_path.write_text("\n".join(lines), encoding="utf-8")
    return str(init_path)
